@port = 3000

### login
# @name loginQuery

POST http://localhost:{{port}}/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin"
}

### GET user

GET http://localhost:{{port}}/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{loginQuery.response.body.access_token}}
